control:
  controller: "lee_attitude_control" # or "lee_velocity_control" or "lee_attitude_control"
  kP: [0.8, 0.8, 1.0] # used for lee_position_control only
  kV: [0.5, 0.5, 0.4] # used for lee_position_control, lee_velocity_control only
  kR: [3.0, 3.0, 1.0] # used for lee_position_control, lee_velocity_control and lee_attitude_control
  kOmega: [0.5, 0.5, 1.20] # used for lee_position_control, lee_velocity_control and lee_attitude_control
  scale_input: [1.0, 1.0, 1.0, 1.0] # scale the input to the controller from -1 to 1 for each dimension, scale from -np.pi to np.pi for yaw in the case of position control

robot_asset:
  collision_mask: 1
  base_link_name: "base_link_0"
  foot_name: "None" # name of the feet bodies, used to index body state and contact force tensors
  penalize_contacts_on: []
  terminate_after_contacts_on: []
  disable_gravity: False
  collapse_fixed_joints: True # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
  fix_base_link: False # fix the base of the robot
  collision_mask: 1 # 1 to disable, 0 to enable...bitwise filter
  replace_cylinder_with_capsule: False # replace collision cylinders with capsules, leads to faster/more stable simulation
  flip_visual_attachments: True # Some .obj meshes must be flipped from y-up to z-up
  density: 0.001
  angular_damping: 0.
  linear_damping: 0.
  max_angular_velocity: 100.
  max_linear_velocity: 100.
  armature: 0.001